### PR TITLE
[#1051] Crashlytics acknowledge

### LINKED ISSUE #1051: Crashlytics acknowledge
We somehow have integrated firebase which implies 2 things:

1. The questions is if we need to do some UI changes because of opt in/out choice of a user

2. if YES, we want to support firebase/crahslytics and we will implement UI, the Question is how to deliver GoogleService-info-plist. This file can't live in repo and must be attached to the project either manually or by CI. We used Bitrise to deliver this automatically but Bitrise is not used anymore. Github secrets would do the same job but it would mean to invest time into CI. The fastest solution is to attach the file to the project manually but it is also fragile because we can easily forgot to do it.

### PR DESCRIPTION
**Pull request by LukasKorba**
Closes #1051 

- Layout changes for the Security warning consent
- The screen has also been refactored to the latest TCA
- Unit tests fixed

NOTE: the screen has also been changed to scrollable due to smaller screens, see the attachments.

Simulator Screenshot - iPhone 15 Pro - 2024-02-20 at 19 25 58
Simulator Screenshot - iPhone SE (3rd generation) - 2024-02-20 at 19 24 21

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Does the code abide by the [Coding Guidelines](../blob/main/docs/CODING_GUIDELINES.md)?
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [x] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/main/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after your changes and when possible, leave it in a better place. [Learn More...](../blob/main/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/main/README.md), [LICENSE.md](../blob/main/LICENSE.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

### CODE REVIEW

File: modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift [hunk 1]
```diff
@@ -18,43 +18,37 @@ import Generated
...
-        }
-
-        @PresentationState public var alert: AlertState<Action>?
+        @Presents public var alert: AlertState<Action>?
         public var appBuild = ""
         public var appVersion = ""
-        public var destination: Destination?
-        @BindingState public var isAcknowledged: Bool = false
+        public var isAcknowledged: Bool = false
+        public var recoveryPhraseDisplayBinding: Bool = false
```
Comment (str4d) [inline modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift:29]: I don't understand what this new variable is for; it is not documented anywhere, and the UI screenshots do not include anything that looks like it might display a recovery phrase.

File: modules/.swiftpm/xcode/xcshareddata/xcschemes/SecurityWarning.xcscheme
Comment (str4d) [inline modules/.swiftpm/xcode/xcshareddata/xcschemes/SecurityWarning.xcscheme:1]: I didn't review this file because I don't know what it does.

File: modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift [hunk 2]
```diff
@@ -18,43 +18,37 @@ import Generated
...
             self.appBuild = appBuild
             self.appVersion = appVersion
-            self.destination = destination
+            self.recoveryPhraseDisplayBinding = recoveryPhraseDisplayBinding
             self.recoveryPhraseDisplayState = recoveryPhraseDisplayState
         }
     }
     
-    public enum Action: BindableAction, Equatable {
+    public enum Action: BindableAction , Equatable {
```
[the remark this answers is not in the document]
Comment (LukasKorba) [reply modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift:45]: fixed

File: modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift (hunk 1 above)
Comment (LukasKorba) [reply modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift:29]: This is a navigational binding to a specific screen, construct in the TCA. I think I refactor it to recoveryPhraseDisplayViewBinding so it's easier for anyone to understand.

File: modules/Sources/Features/SecurityWarning/SecurityWarningView.swift [hunk 3]
```diff
@@ -12,71 +12,74 @@ import UIComponents
...
             .zashiBack()
-            .padding(.horizontal, 60)
-            .alert(store: store.scope(
-                state: \.$alert,
-                action: { .alert($0) }
-            ))
+            .alert($store.scope(state: \.alert, action: \.alert))
             .navigationLinkEmpty(
-                isActive: viewStore.bindingForDestination(.createNewWallet),
+                isActive: $store.recoveryPhraseDisplayBinding,
```
[the remark this answers is not in the document]
Comment (LukasKorba) [reply modules/Sources/Features/SecurityWarning/SecurityWarningView.swift:72]: This is a navigational binding to a specific screen, construct in the TCA. I think I refactor it to recoveryPhraseDisplayViewBinding so it's easier for anyone to understand.

File: modules/.swiftpm/xcode/xcshareddata/xcschemes/SecurityWarning.xcscheme
Comment (LukasKorba) [reply modules/.swiftpm/xcode/xcshareddata/xcschemes/SecurityWarning.xcscheme:1]: Nothing interesting, SW scheme was missing in xcodes schemes and I needed to build just that module. So I added it among other modules. Devs can add/remove such modules whenever they want and .swiftpm reflects that. The problem is we can't add it to the gitignore so it's anoyyingly in PRs from time to time.

https://stackoverflow.com/a/65754189

File: modules/Sources/Generated/L10n.swift [hunk 4]
```diff
@@ -499,18 +499,16 @@ public enum L10n {
...
-    public static let warningPart2 = L10n.tr("Localizable", "securityWarning.warningPart2", fallback: " Users are cautioned to deposit, send, and receive only small amounts of ZEC.")
-    ///  Please click below to proceed.
-    public static let warningPart3 = L10n.tr("Localizable", "securityWarning.warningPart3", fallback: " Please click below to proceed.")
+    /// Zashi %@ (%@) is a Zcash-only, shielded wallet — built by Zcashers for Zcashers. Zashi has been engineered for your privacy and safety. By installing and using Zashi, you consent to share crash reports with Electric Coin Co. (the wallet developer), which will help us improve the Zashi user experience.*
+    public static func warningA(_ p1: Any, _ p2: Any) -> String {
+      return L10n.tr("Localizable", "securityWarning.warningA", String(describing: p1), String(describing: p2), fallback: "Zashi %@ (%@) is a Zcash-only, shielded wallet — built by Zcashers for Zcashers. Zashi has been engineered for your privacy and safety. By installing and using Zashi, you consent to share crash reports with Electric Coin Co. (the wallet developer), which will help us improve the Zashi user experience.*")
```
[the remark this answers is not in the document]
Comment (true-jared) [reply modules/Sources/Generated/L10n.swift:504]: This is a copy we decided for 1.0 and it has been discussed and approved by Chris while reflecting Daira's suggestion. For 1.0 a user cannot opt out - this has been decided by Josh. We can discuss improving it for a later release if you are convinced it is important.

File: modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift [hunk 5]
```diff
@@ -18,43 +18,37 @@ import Generated
...
-        }
-
-        @PresentationState public var alert: AlertState<Action>?
+        @Presents public var alert: AlertState<Action>?
         public var appBuild = ""
         public var appVersion = ""
-        public var destination: Destination?
-        @BindingState public var isAcknowledged: Bool = false
+        public var isAcknowledged: Bool = false
+        public var recoveryPhraseDisplayViewBinding: Bool = false
```
Comment (daira) [inline modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift:29]: Document when this is true, since it's not clear from the name (or use a more obvious name).

File: modules/Sources/Generated/L10n.swift [hunk 6]
```diff
@@ -489,18 +489,16 @@ public enum L10n {
...
+    }
+    /// Please acknowledge and confirm below to proceed.
+    public static let warningB = L10n.tr("Localizable", "securityWarning.warningB", fallback: "Please acknowledge and confirm below to proceed.")
+    /// *Note
+    public static let warningC = L10n.tr("Localizable", "securityWarning.warningC", fallback: "*Note")
```
Comment (daira) [inline modules/Sources/Generated/L10n.swift:499]: Why is there a "*" here?

**Review by daira — APPROVED** [review]
utACK

File: modules/Sources/Generated/L10n.swift (hunk 6 above)
Comment (daira) [reply modules/Sources/Generated/L10n.swift:499]: Never mind, I hadn't seen that it refers back to the "*" at the end of warningA.

File: modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift (hunk 5 above)
Comment (LukasKorba) [reply modules/Sources/Features/SecurityWarning/SecurityWarningStore.swift:31]: Done
